// Generated by CoffeeScript 2.3.0
(function () {
  window.onload = function () {
    var center, galactic_center;
    paper.setup("myCanvas");
    center = paper.view.getCenter();
    galactic_center = new paper.Path(center, center.add([300, 0]));
    galactic_center.strokeColor = 'black';
    jQuery.getJSON("pulsars.json", function (data, status) {
      var pulsars;
      console.log(`Found ${data.length} pulsars`);
      pulsars = convertATNF(data);
      return _.each(pulsars, function (pulsar) {
        return drawPulsar(pulsar, center, 80, 'black', false, 'Verdana', 4, 'regular');
      });
    });
    return paper.view.draw();
  };
}).call(this);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImpzL2FsbC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBLENBQUEsWUFBQTtBQUFBLFNBQUEsTUFBQSxHQUFnQixZQUFBO0FBQ2IsUUFBQSxNQUFBLEVBQUEsZUFBQTtBQUFBLFVBQUEsS0FBQSxDQUFBLFVBQUE7QUFDQSxhQUFTLE1BQU0sSUFBTixDQUFBLFNBQUEsRUFBVDtBQUNBLHNCQUFrQixJQUFJLE1BQUosSUFBQSxDQUFBLE1BQUEsRUFBdUIsT0FBQSxHQUFBLENBQVcsQ0FBQSxHQUFBLEVBQWxDLENBQWtDLENBQVgsQ0FBdkIsQ0FBbEI7QUFDQSxvQkFBQSxXQUFBLEdBQThCLE9BQTlCO0FBQ0EsV0FBQSxPQUFBLENBQUEsY0FBQSxFQUErQixVQUFBLElBQUEsRUFBQSxNQUFBLEVBQUE7QUFDNUIsVUFBQSxPQUFBO0FBQUEsY0FBQSxHQUFBLENBQVksU0FBUyxLQUFULE1BQVosVUFBQTtBQUNBLGdCQUFVLFlBQUEsSUFBQSxDQUFWO2FBQ0EsRUFBQSxJQUFBLENBQUEsT0FBQSxFQUFnQixVQUFBLE1BQUEsRUFBQTtlQUFXLFdBQUEsTUFBQSxFQUFBLE1BQUEsRUFBQSxFQUFBLEVBQUEsT0FBQSxFQUFBLEtBQUEsRUFBQSxTQUFBLEVBQUEsQ0FBQSxFQUFBLFNBQUEsQztBQUEzQixPQUFBLEM7QUFISCxLQUFBO1dBSUEsTUFBTSxJQUFOLENBQUEsSUFBQSxFO0FBVGEsR0FBaEI7Q0FBQSxFLElBQUEsQyxJQUFBIiwic291cmNlc0NvbnRlbnQiOlsiXG53aW5kb3cub25sb2FkID0gLT5cbiAgIHBhcGVyLnNldHVwKFwibXlDYW52YXNcIilcbiAgIGNlbnRlciA9IHBhcGVyLnZpZXcuZ2V0Q2VudGVyKClcbiAgIGdhbGFjdGljX2NlbnRlciA9IG5ldyBwYXBlci5QYXRoIGNlbnRlciwgY2VudGVyLmFkZChbMzAwLDBdKVxuICAgZ2FsYWN0aWNfY2VudGVyLnN0cm9rZUNvbG9yID0gJ2JsYWNrJ1xuICAgalF1ZXJ5LmdldEpTT04gXCJwdWxzYXJzLmpzb25cIiwgKGRhdGEsc3RhdHVzKS0+XG4gICAgICBjb25zb2xlLmxvZyBcIkZvdW5kICN7ZGF0YS5sZW5ndGh9IHB1bHNhcnNcIlxuICAgICAgcHVsc2FycyA9IGNvbnZlcnRBVE5GIGRhdGFcbiAgICAgIF8uZWFjaCBwdWxzYXJzLCAocHVsc2FyKS0+IGRyYXdQdWxzYXIgcHVsc2FyLCBjZW50ZXIsIDgwLCdibGFjaycsIGZhbHNlLCdWZXJkYW5hJyw0LCdyZWd1bGFyJ1xuICAgcGFwZXIudmlldy5kcmF3KClcbiJdLCJzb3VyY2VSb290IjoiLi4ifQ==
//# sourceURL=/Users/thomas/Documents/Projects/Creative/Tattoo/Pulsar map/js/all.coffee